import type { SpotMarker } from '@/types/spot';

export const spotMarkers: SpotMarker[] = [
    {
        id: 'spot-cheongnyangsan',
        contentId: 'mock-cheongnyangsan',
        place_name: '청량산 도립공원',
        region: '봉화군',
        category: 'nature',
        latitude: 36.6393,
        longitude: 129.0317,
        description: '기암절벽과 소나무숲이 어우러진 청정 명산',
    },
    {
        id: 'spot-banbyeoncheon',
        contentId: 'mock-banbyeoncheon',
        place_name: '반변천 생태공원',
        region: '영양군',
        category: 'nature',
        latitude: 36.6666,
        longitude: 129.1122,
        description: '맑은 하천을 따라 걷는 조용한 생태 탐방로',
    },
    {
        id: 'spot-bulyeong-valley',
        contentId: 'mock-bulyeong-valley',
        place_name: '불영계곡',
        region: '울진군',
        category: 'nature',
        latitude: 36.9344,
        longitude: 129.3044,
        description: '협곡과 계류가 빚어낸 굽이굽이 비경',
    },
    {
        id: 'spot-hahoe-village',
        contentId: 'mock-hahoe-village',
        place_name: '안동 하회마을',
        region: '안동시',
        category: 'culture',
        latitude: 36.5335,
        longitude: 128.517,
        description: '전통 가옥과 마을 문화가 살아있는 유네스코 세계유산',
    },
    {
        id: 'spot-donggung-wolji',
        contentId: 'mock-donggung-wolji',
        place_name: '경주 동궁과 월지',
        region: '경주시',
        category: 'night',
        latitude: 35.8347,
        longitude: 129.2248,
        description: '야간 조명이 연못에 비치는 신라 왕궁 터',
    },
    {
        id: 'spot-juwangsan',
        contentId: 'mock-juwangsan',
        place_name: '주왕산 국립공원',
        region: '청송군',
        category: 'nature',
        latitude: 36.3936,
        longitude: 129.1545,
        description: '기암절벽과 폭포가 어우러진 국립공원',
    },
    {
        id: 'spot-sosu-seowon',
        contentId: 'mock-sosu-seowon',
        place_name: '소수서원',
        region: '영주시',
        category: 'culture',
        latitude: 36.8744,
        longitude: 128.6279,
        description: '한국 최초의 사액서원, 고즈넉한 유교 건축',
    },
];
